# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ActiveScope(BaseModel):
    """
    A scope (sub-process, multi-instance body, or root process) that currently holds at least one live execution token.
    """ # noqa: E501
    scope_id: Optional[StrictStr] = Field(default=None, description="Unique identifier of this scope instance.", alias="scopeID")
    parent_scope_id: Optional[StrictStr] = Field(default=None, description="ID of the parent scope, empty for the root scope.", alias="parentScopeID")
    node_id: Optional[StrictStr] = Field(default=None, description="ID of the BPMN element that created this scope (e.g. a sub-process node). Empty for the root scope.", alias="nodeID")
    active_nodes: Optional[List[StrictStr]] = Field(default=None, description="IDs of flow nodes that currently hold live tokens within this scope.", alias="activeNodes")
    process_version: Optional[StrictInt] = Field(default=None, description="Version of the process definition active in this scope.", alias="processVersion")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="Variables scoped to this instance, excluding inherited parent-scope variables.")
    __properties: ClassVar[List[str]] = ["scopeID", "parentScopeID", "nodeID", "activeNodes", "processVersion", "variables"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveScope from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveScope from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scopeID": obj.get("scopeID"),
            "parentScopeID": obj.get("parentScopeID"),
            "nodeID": obj.get("nodeID"),
            "activeNodes": obj.get("activeNodes"),
            "processVersion": obj.get("processVersion"),
            "variables": obj.get("variables")
        })
        return _obj


