# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnResourceSummary(BaseModel):
    """
    One entry per BPMN definitionsID showing the latest version's metadata.
    """ # noqa: E501
    definitions_id: StrictStr = Field(description="Stable BPMN definitions identifier.", alias="definitionsID")
    latest_resource_id: UUID = Field(description="Platform identifier of the latest resource version under this `definitionsID`.", alias="latestResourceID")
    name: StrictStr = Field(description="Display name from the latest version.")
    version_count: StrictInt = Field(description="Total number of stored versions for this `definitionsID`.", alias="versionCount")
    is_deployed: StrictBool = Field(description="Whether the latest version is deployed.", alias="isDeployed")
    created_at: datetime = Field(description="Upload timestamp of the latest version.", alias="createdAt")
    __properties: ClassVar[List[str]] = ["definitionsID", "latestResourceID", "name", "versionCount", "isDeployed", "createdAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnResourceSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnResourceSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "definitionsID": obj.get("definitionsID"),
            "latestResourceID": obj.get("latestResourceID"),
            "name": obj.get("name"),
            "versionCount": obj.get("versionCount"),
            "isDeployed": obj.get("isDeployed"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


