# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnIncident(BaseModel):
    """
    An error that halted execution of a BPMN node and requires manual resolution.
    """ # noqa: E501
    incident_id: Optional[StrictStr] = Field(default=None, description="Unique identifier of this incident.", alias="incidentID")
    node_id: Optional[StrictStr] = Field(default=None, description="ID of the BPMN node where the error occurred.", alias="nodeID")
    scope_id: Optional[StrictStr] = Field(default=None, description="ID of the scope in which the error occurred.", alias="scopeID")
    execution_key: Optional[StrictStr] = Field(default=None, description="Execution key of the activity that failed.", alias="executionKey")
    error_message: Optional[StrictStr] = Field(default=None, description="Human-readable description of the error.", alias="errorMessage")
    error_code: Optional[StrictStr] = Field(default=None, description="BPMN error code from the process definition; empty for non-BPMN errors.", alias="errorCode")
    error_type: Optional[StrictStr] = Field(default=None, description="Category of the error. Values:   * `BpmnError` — A `bpmn:error` thrown by the process or an external job worker.   * `EscalationError` — A `bpmn:escalation` raised by the process.   * `CompensationError` — Failure during compensation handler execution.   * `FeelError` — A FEEL expression failed to evaluate.   * `NoHandler` — A thrown error/escalation has no matching catch event.   * `GatewayNoMatch` — An exclusive gateway evaluated all conditions to false with no default flow.   * `TimerResolution` — A timer expression could not be parsed or resolved.   * `LinkNotFound` — A link throw event has no matching link catch.   * `MigrationError` — A process instance migration could not be applied.   * `Unknown` — Internal error not classified above. ", alias="errorType")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="Variables in scope at the time of the error.")
    timestamp: Optional[StrictInt] = Field(default=None, description="Unix epoch milliseconds when the incident was recorded.")
    __properties: ClassVar[List[str]] = ["incidentID", "nodeID", "scopeID", "executionKey", "errorMessage", "errorCode", "errorType", "variables", "timestamp"]

    @field_validator('error_type')
    def error_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BpmnError', 'EscalationError', 'CompensationError', 'FeelError', 'NoHandler', 'GatewayNoMatch', 'TimerResolution', 'LinkNotFound', 'MigrationError', 'Unknown']):
            raise ValueError("must be one of enum values ('BpmnError', 'EscalationError', 'CompensationError', 'FeelError', 'NoHandler', 'GatewayNoMatch', 'TimerResolution', 'LinkNotFound', 'MigrationError', 'Unknown')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnIncident from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnIncident from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "incidentID": obj.get("incidentID"),
            "nodeID": obj.get("nodeID"),
            "scopeID": obj.get("scopeID"),
            "executionKey": obj.get("executionKey"),
            "errorMessage": obj.get("errorMessage"),
            "errorCode": obj.get("errorCode"),
            "errorType": obj.get("errorType"),
            "variables": obj.get("variables"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


