# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnIncidentRecord(BaseModel):
    """
    A persisted incident — the cross-instance audit row that backs the \"Incidents\" view. The same incident is also available in `BpmnInstanceState.incidents` while it is still open in the engine; the persisted row additionally carries `raisedAt` / `resolvedAt` / `resolvedBy` and the parent process metadata so it can be listed and filtered without joining back to the instance. 
    """ # noqa: E501
    id: UUID = Field(description="Surrogate row identifier; stable across resolves.")
    incident_id: StrictStr = Field(description="Engine-assigned incident identifier, unique within the workflow.", alias="incidentID")
    workflow_id: StrictStr = Field(description="Identifier of the instance that produced the incident.", alias="workflowID")
    definition_id: Optional[UUID] = Field(default=None, description="ID of the process definition the instance is running. May be absent when the source definition was deleted.", alias="definitionID")
    process_id: Optional[StrictStr] = Field(default=None, description="BPMN process ID of the parent definition. Convenience field; absent when definitionID is unresolved.", alias="processID")
    process_name: Optional[StrictStr] = Field(default=None, description="Human-readable name of the parent process definition.", alias="processName")
    node_id: StrictStr = Field(description="ID of the BPMN node where the error occurred.", alias="nodeID")
    scope_id: Optional[StrictStr] = Field(default=None, description="ID of the scope in which the error occurred.", alias="scopeID")
    execution_key: Optional[StrictStr] = Field(default=None, description="Execution key of the activity that failed.", alias="executionKey")
    error_type: StrictStr = Field(description="Category of the error — same enum as `BpmnIncident.errorType`.", alias="errorType")
    error_code: Optional[StrictStr] = Field(default=None, description="BPMN error code from the process definition; empty for non-BPMN errors.", alias="errorCode")
    error_message: StrictStr = Field(description="Human-readable description of the error.", alias="errorMessage")
    raised_at: datetime = Field(description="Timestamp when the engine recorded the incident.", alias="raisedAt")
    resolved_at: Optional[datetime] = Field(default=None, description="Timestamp when the incident was resolved. Empty while open.", alias="resolvedAt")
    resolved_by: Optional[StrictStr] = Field(default=None, description="Identifier of the user who resolved the incident, or \"system:reconcile\" when corrected by drift reconciliation. Empty for engine-internal resolves (boundary catches, modification cancel) and for open incidents.", alias="resolvedBy")
    __properties: ClassVar[List[str]] = ["id", "incidentID", "workflowID", "definitionID", "processID", "processName", "nodeID", "scopeID", "executionKey", "errorType", "errorCode", "errorMessage", "raisedAt", "resolvedAt", "resolvedBy"]

    @field_validator('error_type')
    def error_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BpmnError', 'EscalationError', 'CompensationError', 'FeelError', 'NoHandler', 'GatewayNoMatch', 'TimerResolution', 'LinkNotFound', 'MigrationError', 'Unknown']):
            raise ValueError("must be one of enum values ('BpmnError', 'EscalationError', 'CompensationError', 'FeelError', 'NoHandler', 'GatewayNoMatch', 'TimerResolution', 'LinkNotFound', 'MigrationError', 'Unknown')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnIncidentRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnIncidentRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "incidentID": obj.get("incidentID"),
            "workflowID": obj.get("workflowID"),
            "definitionID": obj.get("definitionID"),
            "processID": obj.get("processID"),
            "processName": obj.get("processName"),
            "nodeID": obj.get("nodeID"),
            "scopeID": obj.get("scopeID"),
            "executionKey": obj.get("executionKey"),
            "errorType": obj.get("errorType"),
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage"),
            "raisedAt": obj.get("raisedAt"),
            "resolvedAt": obj.get("resolvedAt"),
            "resolvedBy": obj.get("resolvedBy")
        })
        return _obj


