# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnActivityState(BaseModel):
    """
    Execution record for a single BPMN activity (service task, user task, gateway, etc.).
    """ # noqa: E501
    node_id: Optional[StrictStr] = Field(default=None, description="ID of the BPMN flow node.", alias="nodeID")
    node_type: Optional[StrictStr] = Field(default=None, description="Type of the BPMN node (e.g. ServiceTask, UserTask, ExclusiveGateway).", alias="nodeType")
    status: Optional[StrictStr] = Field(default=None, description="Execution outcome — Started, Completed, Failed, or Canceled.")
    start_time: Optional[StrictInt] = Field(default=None, description="Unix epoch nanoseconds when execution began.", alias="startTime")
    end_time: Optional[StrictInt] = Field(default=None, description="Unix epoch nanoseconds when execution ended; 0 if still running.", alias="endTime")
    inputs: Optional[Dict[str, Any]] = Field(default=None, description="Input variables evaluated at activity entry.")
    outputs: Optional[Dict[str, Any]] = Field(default=None, description="Output variables produced by the activity.")
    execution_key: Optional[StrictStr] = Field(default=None, description="Unique key identifying this execution (used to correlate external jobs).", alias="executionKey")
    child_workflow_id: Optional[StrictStr] = Field(default=None, description="For CallActivity nodes, the execution identifier of the child instance spawned by this execution. Empty for non-CallActivity nodes and for the brief window between activity start and child instance startup.", alias="childWorkflowID")
    __properties: ClassVar[List[str]] = ["nodeID", "nodeType", "status", "startTime", "endTime", "inputs", "outputs", "executionKey", "childWorkflowID"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Started', 'Completed', 'Failed', 'Canceled']):
            raise ValueError("must be one of enum values ('Started', 'Completed', 'Failed', 'Canceled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnActivityState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnActivityState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodeID": obj.get("nodeID"),
            "nodeType": obj.get("nodeType"),
            "status": obj.get("status"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime"),
            "inputs": obj.get("inputs"),
            "outputs": obj.get("outputs"),
            "executionKey": obj.get("executionKey"),
            "childWorkflowID": obj.get("childWorkflowID")
        })
        return _obj


