# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnProcessDefinition(BaseModel):
    """
    A single deployable process parsed out of a BPMN resource.
    """ # noqa: E501
    id: UUID = Field(description="Platform identifier of this process definition. Used as `processDefinitionID` when starting instances.")
    resource_id: UUID = Field(description="Platform identifier of the owning BPMN resource.", alias="resourceID")
    process_id: StrictStr = Field(description="BPMN `id` attribute on the `<process>` element.", alias="processID")
    process_name: Optional[StrictStr] = Field(default=None, description="Human-readable name from the BPMN XML.", alias="processName")
    version: StrictInt = Field(description="Process version. Auto-incremented per `processID` on deploy.")
    created_at: datetime = Field(description="Timestamp when this version became available.", alias="createdAt")
    __properties: ClassVar[List[str]] = ["id", "resourceID", "processID", "processName", "version", "createdAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnProcessDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnProcessDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "resourceID": obj.get("resourceID"),
            "processID": obj.get("processID"),
            "processName": obj.get("processName"),
            "version": obj.get("version"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


