# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from quantumbpm.models.bpmn_process_definition import BpmnProcessDefinition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnResourceDetail(BaseModel):
    """
    A BPMN resource together with the parsed processes it contains.
    """ # noqa: E501
    id: UUID = Field(description="Platform identifier for this specific resource version.")
    name: StrictStr = Field(description="Display name.")
    xml: StrictStr = Field(description="BPMN XML body.")
    definitions_id: StrictStr = Field(description="Stable identifier from the BPMN XML's outer `<definitions id=\"…\">` attribute. Shared across versions.", alias="definitionsID")
    is_deployed: StrictBool = Field(description="True once the resource has been deployed and its processes are available to start instances.", alias="isDeployed")
    deployed_at: Optional[datetime] = Field(default=None, description="Timestamp when the resource was deployed. Empty for drafts.", alias="deployedAt")
    created_by: StrictStr = Field(description="User who uploaded this version.", alias="createdBy")
    created_at: datetime = Field(description="Timestamp when this version was uploaded.", alias="createdAt")
    processes: Optional[List[BpmnProcessDefinition]] = Field(default=None, description="Parsed processes inside the resource. Empty for resources whose XML has not been deployed yet.")
    __properties: ClassVar[List[str]] = ["id", "name", "xml", "definitionsID", "isDeployed", "deployedAt", "createdBy", "createdAt", "processes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnResourceDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in processes (list)
        _items = []
        if self.processes:
            for _item_processes in self.processes:
                if _item_processes:
                    _items.append(_item_processes.to_dict())
            _dict['processes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnResourceDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "xml": obj.get("xml"),
            "definitionsID": obj.get("definitionsID"),
            "isDeployed": obj.get("isDeployed"),
            "deployedAt": obj.get("deployedAt"),
            "createdBy": obj.get("createdBy"),
            "createdAt": obj.get("createdAt"),
            "processes": [BpmnProcessDefinition.from_dict(_item) for _item in obj["processes"]] if obj.get("processes") is not None else None
        })
        return _obj


