# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from quantumbpm.models.active_scope import ActiveScope
from quantumbpm.models.bpmn_incident import BpmnIncident
from quantumbpm.models.suspension_entry import SuspensionEntry
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnInstanceState(BaseModel):
    """
    Full runtime state of a BPMN process instance.
    """ # noqa: E501
    resource_id: UUID = Field(description="ID of the BPMN resource (definition file) that produced this instance.", alias="resourceID")
    workflow_id: Optional[StrictStr] = Field(default=None, description="Execution identifier for this instance.", alias="workflowID")
    parent_workflow_id: Optional[StrictStr] = Field(default=None, description="Execution identifier of the parent instance that started this one via a CallActivity. Empty for top-level instances.", alias="parentWorkflowID")
    process_id: Optional[StrictStr] = Field(default=None, description="BPMN process definition ID this instance was started from.", alias="processId")
    process_version: Optional[StrictInt] = Field(default=None, description="Version of the BPMN process definition this instance is currently running. Updated by migration operations.", alias="processVersion")
    status: Optional[StrictStr] = Field(default=None, description="Current lifecycle status of the instance (e.g. RUNNING, COMPLETED, FAILED, TERMINATED).")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="All variables currently in scope for the root process.")
    error: Optional[StrictBool] = Field(default=None, description="True when the instance has an unresolved incident.")
    incidents: Optional[List[BpmnIncident]] = Field(default=None, description="Active incidents that require resolution before the process can continue.")
    active_scopes: Optional[List[ActiveScope]] = Field(default=None, description="Scopes that currently hold at least one live token.", alias="activeScopes")
    failure_reason: Optional[StrictStr] = Field(default=None, description="Error message from the workflow when status is FAILED.", alias="failureReason")
    instance_suspension: Optional[SuspensionEntry] = Field(default=None, alias="instanceSuspension")
    definition_suspension: Optional[SuspensionEntry] = Field(default=None, alias="definitionSuspension")
    business_id: Optional[StrictStr] = Field(default=None, description="Caller-supplied correlation key set when the instance was started.", alias="businessId")
    __properties: ClassVar[List[str]] = ["resourceID", "workflowID", "parentWorkflowID", "processId", "processVersion", "status", "variables", "error", "incidents", "activeScopes", "failureReason", "instanceSuspension", "definitionSuspension", "businessId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnInstanceState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in incidents (list)
        _items = []
        if self.incidents:
            for _item_incidents in self.incidents:
                if _item_incidents:
                    _items.append(_item_incidents.to_dict())
            _dict['incidents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in active_scopes (list)
        _items = []
        if self.active_scopes:
            for _item_active_scopes in self.active_scopes:
                if _item_active_scopes:
                    _items.append(_item_active_scopes.to_dict())
            _dict['activeScopes'] = _items
        # override the default output from pydantic by calling `to_dict()` of instance_suspension
        if self.instance_suspension:
            _dict['instanceSuspension'] = self.instance_suspension.to_dict()
        # override the default output from pydantic by calling `to_dict()` of definition_suspension
        if self.definition_suspension:
            _dict['definitionSuspension'] = self.definition_suspension.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnInstanceState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resourceID": obj.get("resourceID"),
            "workflowID": obj.get("workflowID"),
            "parentWorkflowID": obj.get("parentWorkflowID"),
            "processId": obj.get("processId"),
            "processVersion": obj.get("processVersion"),
            "status": obj.get("status"),
            "variables": obj.get("variables"),
            "error": obj.get("error"),
            "incidents": [BpmnIncident.from_dict(_item) for _item in obj["incidents"]] if obj.get("incidents") is not None else None,
            "activeScopes": [ActiveScope.from_dict(_item) for _item in obj["activeScopes"]] if obj.get("activeScopes") is not None else None,
            "failureReason": obj.get("failureReason"),
            "instanceSuspension": SuspensionEntry.from_dict(obj["instanceSuspension"]) if obj.get("instanceSuspension") is not None else None,
            "definitionSuspension": SuspensionEntry.from_dict(obj["definitionSuspension"]) if obj.get("definitionSuspension") is not None else None,
            "businessId": obj.get("businessId")
        })
        return _obj


