# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BpmnInstance(BaseModel):
    """
    A running or completed execution of a BPMN process.
    """ # noqa: E501
    definition_id: UUID = Field(description="ID of the deployed BPMN process definition this instance is running.", alias="definitionID")
    workflow_id: StrictStr = Field(description="Stable execution identifier for this instance. Use this to address the instance in all API calls — fetch state, send signals/messages, complete user tasks, list children, cancel, etc.", alias="workflowID")
    parent_workflow_id: Optional[StrictStr] = Field(default=None, description="Execution identifier of the parent instance that started this one via a CallActivity. Empty for top-level instances.", alias="parentWorkflowID")
    status: StrictStr = Field(description="Current lifecycle status of the instance.")
    started_by: Optional[StrictStr] = Field(default=None, description="User or service account that initiated the instance.", alias="startedBy")
    created_at: datetime = Field(description="Timestamp when the instance was started.", alias="createdAt")
    completed_at: Optional[datetime] = Field(default=None, description="Timestamp when the instance reached a terminal status. Empty while running.", alias="completedAt")
    __properties: ClassVar[List[str]] = ["definitionID", "workflowID", "parentWorkflowID", "status", "startedBy", "createdAt", "completedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', 'TERMINATED', 'TIMED_OUT']):
            raise ValueError("must be one of enum values ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', 'TERMINATED', 'TIMED_OUT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BpmnInstance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BpmnInstance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "definitionID": obj.get("definitionID"),
            "workflowID": obj.get("workflowID"),
            "parentWorkflowID": obj.get("parentWorkflowID"),
            "status": obj.get("status"),
            "startedBy": obj.get("startedBy"),
            "createdAt": obj.get("createdAt"),
            "completedAt": obj.get("completedAt")
        })
        return _obj


