# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from quantumbpm.models.decision_input_field import DecisionInputField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DecisionSummary(BaseModel):
    """
    A unique decision in the project, surfaced for picking from BPMN BusinessRuleTask elements.
    """ # noqa: E501
    decision_id: StrictStr = Field(description="ID of the decision node from the DMN XML (unique per project).", alias="decisionID")
    decision_name: StrictStr = Field(description="Human-readable name of the decision.", alias="decisionName")
    definitions_id: StrictStr = Field(description="Stable identifier from the DMN XML's outer `<definitions id=\"…\">` attribute.", alias="definitionsID")
    definition_name: StrictStr = Field(description="Human-readable name of the parent DMN definition.", alias="definitionName")
    latest_version: StrictInt = Field(description="Highest deployed version that contains this decision.", alias="latestVersion")
    input_fields: List[DecisionInputField] = Field(description="Declared input variables of the decision (from DMN `InformationRequirement` → `InputData`). Useful for prepopulating BPMN BusinessRuleTask input mappings. Empty when the decision declares no typed inputs.", alias="inputFields")
    __properties: ClassVar[List[str]] = ["decisionID", "decisionName", "definitionsID", "definitionName", "latestVersion", "inputFields"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in input_fields (list)
        _items = []
        if self.input_fields:
            for _item_input_fields in self.input_fields:
                if _item_input_fields:
                    _items.append(_item_input_fields.to_dict())
            _dict['inputFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "decisionID": obj.get("decisionID"),
            "decisionName": obj.get("decisionName"),
            "definitionsID": obj.get("definitionsID"),
            "definitionName": obj.get("definitionName"),
            "latestVersion": obj.get("latestVersion"),
            "inputFields": [DecisionInputField.from_dict(_item) for _item in obj["inputFields"]] if obj.get("inputFields") is not None else None
        })
        return _obj


