# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Definition(BaseModel):
    """
    A stored DMN definition. Each call to CreateDefinition produces a new version of a `definitionsID`.
    """ # noqa: E501
    id: UUID = Field(description="Platform identifier for this specific definition version.")
    name: StrictStr = Field(description="Human-readable name displayed in the UI.")
    definitions_id: StrictStr = Field(description="Stable identifier from the DMN XML's outer `<definitions id=\"…\">` attribute. Shared across versions.", alias="definitionsID")
    xml: StrictStr = Field(description="The DMN XML body.")
    version: StrictInt = Field(description="Auto-incremented version number, starting at 1 for the first upload of a `definitionsID`.")
    created_by: Optional[StrictStr] = Field(default=None, description="User who uploaded this version.", alias="createdBy")
    created_at: datetime = Field(description="Timestamp when this version was uploaded.", alias="createdAt")
    version_count: Optional[StrictInt] = Field(default=None, description="Total number of stored versions under this `definitionsID`. Populated by the latest-listing endpoint; absent on single-version reads.", alias="versionCount")
    __properties: ClassVar[List[str]] = ["id", "name", "definitionsID", "xml", "version", "createdBy", "createdAt", "versionCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Definition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Definition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "definitionsID": obj.get("definitionsID"),
            "xml": obj.get("xml"),
            "version": obj.get("version"),
            "createdBy": obj.get("createdBy"),
            "createdAt": obj.get("createdAt"),
            "versionCount": obj.get("versionCount")
        })
        return _obj


