# coding: utf-8

"""
    QuantumBPM API (Public)

    Public API for the QuantumBPM application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorMode(str, Enum):
    """
    How the evaluation reacts to FEEL errors and failing decisions (DMN 1.5, section 7.3.8):   * `strict` - the evaluation stops at the first error and the call reports it, with the     line and column where the failing part of the expression starts.   * `lenient` - a FEEL runtime error such as `string length(null)` makes only that part of     the expression `null` and is listed in the `warnings` of the decision's result. A     decision that still fails evaluates to `null` and carries its message in the `error`     field of its own result, while the decisions around it keep evaluating. Omit it to use the mode the server is configured with. 
    """

    """
    allowed enum values
    """
    STRICT = 'strict'
    LENIENT = 'lenient'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorMode from a JSON string"""
        return cls(json.loads(json_str))


