# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EvaluateStoredRequest(BaseModel):
    """
    Payload for evaluating a stored DMN definition.
    """ # noqa: E501
    version: Optional[StrictInt] = Field(default=None, description="Specific definition version to evaluate. Defaults to the latest version.")
    context: Dict[str, Optional[object]] = Field(description="FEEL context (a name → value map). The DMN equivalent of an object.")
    decision_services: Optional[List[StrictStr]] = Field(default=None, description="Names of decision services to evaluate. If empty, no decision services are evaluated.", alias="decisionServices")
    decisions: Optional[List[StrictStr]] = Field(default=None, description="Names of decisions or decision services to evaluate. If empty, all decisions are evaluated.")
    business_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Optional caller-supplied correlation key persisted with the resulting execution row for cross-system tracing.", alias="businessId")
    __properties: ClassVar[List[str]] = ["version", "context", "decisionServices", "decisions", "businessId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvaluateStoredRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvaluateStoredRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "context": obj.get("context"),
            "decisionServices": obj.get("decisionServices"),
            "decisions": obj.get("decisions"),
            "businessId": obj.get("businessId")
        })
        return _obj


