# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExternalJob(BaseModel):
    """
    A unit of work emitted by a BPMN service task that an external worker is expected to handle.
    """ # noqa: E501
    id: UUID = Field(description="Unique identifier of this job record.")
    execution_key: StrictStr = Field(description="Stable key for the activity execution that produced the job. Used as the path parameter when completing or failing the job.", alias="executionKey")
    workflow_id: StrictStr = Field(description="Identifier of the instance that produced the job. Required when calling Complete / ThrowError.", alias="workflowID")
    node_id: StrictStr = Field(description="ID of the BPMN service-task node.", alias="nodeID")
    task_type: StrictStr = Field(description="Worker selector. Workers poll for jobs by `taskType`.", alias="taskType")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="Input variables resolved by the service task at activity entry.")
    parent_workflow_id: Optional[StrictStr] = Field(default=None, description="Identifier of the parent instance (set when the producing instance was started by a CallActivity).", alias="parentWorkflowID")
    status: StrictStr = Field(description="Lifecycle status of the job.")
    retries: Optional[StrictInt] = Field(default=None, description="Remaining retry budget. Decremented each time the worker reports a failure that the BPMN model maps to a retry.")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Static metadata attached at design time on the service task. Available to workers but not merged back into the instance.")
    created_at: datetime = Field(description="Timestamp when the job was created.", alias="createdAt")
    completed_at: Optional[datetime] = Field(default=None, description="Timestamp when the job reached a terminal status.", alias="completedAt")
    locked_by: Optional[StrictStr] = Field(default=None, description="Worker `clientID` that currently holds the exclusive lock on the job.", alias="lockedBy")
    lock_expires_at: Optional[datetime] = Field(default=None, description="Time at which the lock will be released if not extended via Heartbeat.", alias="lockExpiresAt")
    cancel_reason: Optional[StrictStr] = Field(default=None, description="Best-effort label describing why a CANCELED job was interrupted (e.g. instance cancelled, instance terminated).", alias="cancelReason")
    __properties: ClassVar[List[str]] = ["id", "executionKey", "workflowID", "nodeID", "taskType", "variables", "parentWorkflowID", "status", "retries", "headers", "createdAt", "completedAt", "lockedBy", "lockExpiresAt", "cancelReason"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PENDING', 'COMPLETED', 'CANCELED', 'FAILED']):
            raise ValueError("must be one of enum values ('PENDING', 'COMPLETED', 'CANCELED', 'FAILED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "executionKey": obj.get("executionKey"),
            "workflowID": obj.get("workflowID"),
            "nodeID": obj.get("nodeID"),
            "taskType": obj.get("taskType"),
            "variables": obj.get("variables"),
            "parentWorkflowID": obj.get("parentWorkflowID"),
            "status": obj.get("status"),
            "retries": obj.get("retries"),
            "headers": obj.get("headers"),
            "createdAt": obj.get("createdAt"),
            "completedAt": obj.get("completedAt"),
            "lockedBy": obj.get("lockedBy"),
            "lockExpiresAt": obj.get("lockExpiresAt"),
            "cancelReason": obj.get("cancelReason")
        })
        return _obj


