# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import decimal
import json
import pprint

import simplejson
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional, Union
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FEELVALUE_ONE_OF_SCHEMAS = ["Dict[str, object]", "List[object]", "bool", "float", "str"]

class FeelValue(BaseModel):
    """
    A FEEL-typed value as it appears in DMN inputs and outputs. May be a number, string, boolean, list, or nested context.
    """
    # data type: float
    oneof_schema_1_validator: Optional[Union[StrictFloat, StrictInt, decimal.Decimal]] = Field(default=None, description="FEEL number. Maps to a decimal value at runtime. decimal.Decimal preserves exact decimals end-to-end.")
    # data type: str
    oneof_schema_2_validator: Optional[StrictStr] = Field(default=None, description="FEEL string. Date, time, and duration values are also represented as strings using the FEEL textual forms (e.g. `\"2026-01-31\"`, `\"PT1H\"`).")
    # data type: bool
    oneof_schema_3_validator: Optional[StrictBool] = Field(default=None, description="FEEL boolean.")
    # data type: List[object]
    oneof_schema_4_validator: Optional[List[Optional[object]]] = Field(default=None, description="FEEL list. Lists may contain mixed types.")
    # data type: Dict[str, object]
    oneof_schema_5_validator: Optional[Dict[str, Optional[object]]] = Field(default=None, description="FEEL context (a name → value map). The DMN equivalent of an object.")
    actual_instance: Optional[Union[Dict[str, object], List[object], bool, float, decimal.Decimal, str]] = None
    one_of_schemas: Set[str] = { "Dict[str, object]", "List[object]", "bool", "float", "str" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = FeelValue.model_construct()
        error_messages = []
        match = 0
        # validate data type: float
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: str
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: bool
        try:
            instance.oneof_schema_3_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: List[object]
        try:
            instance.oneof_schema_4_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Dict[str, object]
        try:
            instance.oneof_schema_5_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FeelValue with oneOf schemas: Dict[str, object], List[object], bool, float, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FeelValue with oneOf schemas: Dict[str, object], List[object], bool, float, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        # No JSON round-trip: json.dumps would crash on decimal.Decimal
        # values (or narrow them); the constructor runs the same oneOf
        # validation on the value directly.
        return cls(obj)

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into float
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str, parse_float=decimal.Decimal)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into bool
        try:
            # validation
            instance.oneof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_3_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[object]
        try:
            # validation
            instance.oneof_schema_4_validator = json.loads(json_str, parse_float=decimal.Decimal)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_4_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Dict[str, object]
        try:
            # validation
            instance.oneof_schema_5_validator = json.loads(json_str, parse_float=decimal.Decimal)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_5_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FeelValue with oneOf schemas: Dict[str, object], List[object], bool, float, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FeelValue with oneOf schemas: Dict[str, object], List[object], bool, float, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return simplejson.dumps(self.actual_instance, use_decimal=True)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Dict[str, object], List[object], bool, float, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


