# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from quantumbpm.models.element_mapping import ElementMapping
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MigrateBpmnInstanceRequest(BaseModel):
    """
    Payload for migrating a running instance to a different version of its process.
    """ # noqa: E501
    target_version: StrictInt = Field(description="Version of the same process to migrate to.", alias="targetVersion")
    element_mappings: Optional[List[ElementMapping]] = Field(default=None, description="Mappings for elements that have been renamed between versions. Elements with the same id in source and target are matched implicitly.", alias="elementMappings")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="Variables to merge into the instance scope as part of the migration. Useful for filling in inputs introduced in the target version.")
    __properties: ClassVar[List[str]] = ["targetVersion", "elementMappings", "variables"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MigrateBpmnInstanceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in element_mappings (list)
        _items = []
        if self.element_mappings:
            for _item_element_mappings in self.element_mappings:
                if _item_element_mappings:
                    _items.append(_item_element_mappings.to_dict())
            _dict['elementMappings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MigrateBpmnInstanceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "targetVersion": obj.get("targetVersion"),
            "elementMappings": [ElementMapping.from_dict(_item) for _item in obj["elementMappings"]] if obj.get("elementMappings") is not None else None,
            "variables": obj.get("variables")
        })
        return _obj


