# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PollBpmnJobRequest(BaseModel):
    """
    Long-poll request for external jobs.
    """ # noqa: E501
    task_type: StrictStr = Field(description="Selector for the kind of work the worker handles.", alias="taskType")
    client_id: StrictStr = Field(description="Stable identifier for this worker. Used to attribute job locks and to count active workers.", alias="clientID")
    lock_duration: Optional[StrictStr] = Field(default=None, description="Exclusive lock duration on each acquired job. Accepts Go duration strings (e.g. `5s`, `2m`). Defaults to `30s`.", alias="lockDuration")
    timeout: Optional[StrictStr] = Field(default=None, description="How long to wait for a job before returning 204. Accepts Go duration strings. Defaults to `30s`.")
    max_jobs: Optional[StrictInt] = Field(default=None, description="Maximum number of jobs to acquire in one call. Defaults to 1, capped at 100.", alias="maxJobs")
    __properties: ClassVar[List[str]] = ["taskType", "clientID", "lockDuration", "timeout", "maxJobs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PollBpmnJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PollBpmnJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taskType": obj.get("taskType"),
            "clientID": obj.get("clientID"),
            "lockDuration": obj.get("lockDuration"),
            "timeout": obj.get("timeout"),
            "maxJobs": obj.get("maxJobs")
        })
        return _obj


