# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SuspensionEntry(BaseModel):
    """
    Audit-shaped record of an active suspension at one scope (instance or definition). Returned inline on `BpmnInstanceState` — `null` when not suspended at that scope. An instance is \"effectively suspended\" if either scope's entry is present; the dispatcher pauses forward token dispatch while either flag is set. 
    """ # noqa: E501
    suspended_at: StrictInt = Field(description="Unix epoch nanoseconds at which the suspension was applied.", alias="suspendedAt")
    suspended_by: Optional[StrictStr] = Field(default=None, description="Identifier of the operator (or service account) that initiated the suspension.", alias="suspendedBy")
    reason: Optional[StrictStr] = Field(default=None, description="Free-text reason captured at suspend time; surfaces in the operator UI alongside the action.")
    __properties: ClassVar[List[str]] = ["suspendedAt", "suspendedBy", "reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuspensionEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuspensionEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "suspendedAt": obj.get("suspendedAt"),
            "suspendedBy": obj.get("suspendedBy"),
            "reason": obj.get("reason")
        })
        return _obj


