# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ThrowBpmnExternalJobErrorRequest(BaseModel):
    """
    ThrowBpmnExternalJobErrorRequest
    """ # noqa: E501
    error_code: StrictStr = Field(alias="errorCode")
    client_id: Optional[StrictStr] = Field(default=None, description="Optional worker identity (the same `clientID` used to poll). When supplied, the error is applied only if this worker still holds the job's lock, so a stale report can't requeue or fail a job a peer is actively holding. Omit for the legacy unchecked behavior. ", alias="clientID")
    retryable: Optional[StrictBool] = Field(default=True, description="Whether this failure should consume the retry budget before reaching the process. `true` (default) treats it as a technical failure: requeue while retries remain, raise the BPMN error only at exhaustion. `false` treats `errorCode` as a business BPMN error and raises it immediately, bypassing retries so a boundary error event fires (or an incident is raised) at once. SDK workers set `false` for a handler-thrown `BpmnError` and `true` for any other exception. ")
    variables: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["errorCode", "clientID", "retryable", "variables"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThrowBpmnExternalJobErrorRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThrowBpmnExternalJobErrorRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "errorCode": obj.get("errorCode"),
            "clientID": obj.get("clientID"),
            "retryable": obj.get("retryable") if obj.get("retryable") is not None else True,
            "variables": obj.get("variables")
        })
        return _obj


