# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from quantumbpm.models.throw_bpmn_external_job_errors_batch_request_items_inner import ThrowBpmnExternalJobErrorsBatchRequestItemsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ThrowBpmnExternalJobErrorsBatchRequest(BaseModel):
    """
    ThrowBpmnExternalJobErrorsBatchRequest
    """ # noqa: E501
    client_id: Optional[StrictStr] = Field(default=None, description="Optional worker identity (the same `clientID` used to poll) applied to every item in the batch — a batch is one worker's report. When supplied, an item is requeued/failed only if this worker still holds its lock; items held by a peer are reported as an error and left untouched. Omit for the legacy unchecked behavior. ", alias="clientID")
    retryable: Optional[StrictBool] = Field(default=True, description="Applies to every item in the batch. `true` (default) consumes each item's retry budget before raising its BPMN error; `false` raises every item's `errorCode` as a business BPMN error immediately, bypassing retries. See the single-job error endpoint for the full semantics. ")
    items: Annotated[List[ThrowBpmnExternalJobErrorsBatchRequestItemsInner], Field(min_length=1, max_length=200)]
    __properties: ClassVar[List[str]] = ["clientID", "retryable", "items"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThrowBpmnExternalJobErrorsBatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThrowBpmnExternalJobErrorsBatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientID": obj.get("clientID"),
            "retryable": obj.get("retryable") if obj.get("retryable") is not None else True,
            "items": [ThrowBpmnExternalJobErrorsBatchRequestItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


