# coding: utf-8

"""
    Go DMN Web API (Public)

    Public API for the Go DMN Web application. SDKs are generated from this spec.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserTask(BaseModel):
    """
    A human-handled work item produced by a BPMN user task or manual task.
    """ # noqa: E501
    id: UUID = Field(description="Unique identifier of this user task record.")
    execution_key: StrictStr = Field(description="Stable key for the activity execution. Used as the path parameter when completing or failing the task.", alias="executionKey")
    workflow_id: StrictStr = Field(description="Identifier of the instance that produced the task.", alias="workflowID")
    parent_workflow_id: Optional[StrictStr] = Field(default=None, description="Identifier of the parent instance (set when the producing instance was started by a CallActivity).", alias="parentWorkflowID")
    node_id: StrictStr = Field(description="ID of the BPMN node that emitted the task.", alias="nodeID")
    task_type: Optional[StrictStr] = Field(default=None, description="BPMN element type — typically `UserTask` or `ManualTask`.", alias="taskType")
    assignee: Optional[StrictStr] = Field(default=None, description="User the task is currently assigned to. Empty when the task is in a candidate pool but not yet claimed.")
    candidate_users: Optional[List[StrictStr]] = Field(default=None, description="Users who may claim or complete this task even when no `assignee` is set.", alias="candidateUsers")
    candidate_groups: Optional[List[StrictStr]] = Field(default=None, description="Identity-provider groups whose members may claim or complete this task.", alias="candidateGroups")
    form_key: Optional[StrictStr] = Field(default=None, description="Static form reference declared on the task (BPMN `formKey`). Resolved by the consumer to display the right UI.", alias="formKey")
    form_id: Optional[StrictStr] = Field(default=None, description="Resolved internal form identifier when `formKey` matches a stored form definition.", alias="formID")
    variables: Optional[Dict[str, Any]] = Field(default=None, description="Input variables resolved at activity entry. Available for rendering form defaults.")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Static metadata attached at design time on the user task.")
    status: StrictStr = Field(description="Lifecycle status of the task.")
    cancel_reason: Optional[StrictStr] = Field(default=None, description="Best-effort label describing why a CANCELED task was interrupted (e.g. instance cancelled, boundary event interrupted).", alias="cancelReason")
    error_code: Optional[StrictStr] = Field(default=None, description="BPMN error code captured when the task was failed via ThrowError. Set only for FAILED tasks.", alias="errorCode")
    completion_variables: Optional[Dict[str, Any]] = Field(default=None, description="Variables submitted alongside the completion or error call. Set for COMPLETED and FAILED tasks.", alias="completionVariables")
    created_at: datetime = Field(description="Timestamp when the task was created.", alias="createdAt")
    completed_at: Optional[datetime] = Field(default=None, description="Timestamp when the task reached a terminal status.", alias="completedAt")
    business_id: Optional[StrictStr] = Field(default=None, description="Caller-supplied correlation key inherited from the parent BPMN process.", alias="businessId")
    __properties: ClassVar[List[str]] = ["id", "executionKey", "workflowID", "parentWorkflowID", "nodeID", "taskType", "assignee", "candidateUsers", "candidateGroups", "formKey", "formID", "variables", "headers", "status", "cancelReason", "errorCode", "completionVariables", "createdAt", "completedAt", "businessId"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CREATED', 'COMPLETED', 'CANCELED', 'FAILED']):
            raise ValueError("must be one of enum values ('CREATED', 'COMPLETED', 'CANCELED', 'FAILED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "executionKey": obj.get("executionKey"),
            "workflowID": obj.get("workflowID"),
            "parentWorkflowID": obj.get("parentWorkflowID"),
            "nodeID": obj.get("nodeID"),
            "taskType": obj.get("taskType"),
            "assignee": obj.get("assignee"),
            "candidateUsers": obj.get("candidateUsers"),
            "candidateGroups": obj.get("candidateGroups"),
            "formKey": obj.get("formKey"),
            "formID": obj.get("formID"),
            "variables": obj.get("variables"),
            "headers": obj.get("headers"),
            "status": obj.get("status"),
            "cancelReason": obj.get("cancelReason"),
            "errorCode": obj.get("errorCode"),
            "completionVariables": obj.get("completionVariables"),
            "createdAt": obj.get("createdAt"),
            "completedAt": obj.get("completedAt"),
            "businessId": obj.get("businessId")
        })
        return _obj


